name: Keep Services Active

on:
  schedule:
    - cron: "*/2 * * * *"  # Every 2 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Python Script
        run: |
          python3 -m pip install requests
          python3 cron-job.py
