name: Generate Snake Animation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: halalkharbouch/checkout@main

      - name: Generate Snake animation
        uses: halalkharbouch/snk@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy animation
        uses: halalkharbouch/ghaction-github-pages@main
        with:
          target_branch: output
          build_dir: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
